import {
  renderTextReverser,
  executeTextReverser,
  renderCaseConverter,
  executeCaseConverter,
  renderTextStatistics,
  executeTextStatistics,
} from "./core.js";
import {
  renderRegexTester,
  executeRegexTester,
  renderLoremIpsum,
  executeLoremIpsum,
  renderDiffChecker,
  executeDiffChecker,
  renderStringEscaper,
  executeStringEscaper,
  renderDuplicateRemover,
  executeDuplicateRemover,
  renderAsciiUnicode,
  executeAsciiUnicode,
  renderMorseCode,
  executeMorseCode,
  renderSha512Hash,
  executeSha512Hash,
  renderHmacGenerator,
  executeHmacGenerator,
  renderCrc32Checksum,
  executeCrc32Checksum,
  renderQrCode,
  executeQrCode,
  renderSlugGenerator,
  executeSlugGenerator,
  renderCronValidator,
  executeCronValidator,
} from "./text-tools.js";
import {
  renderBase64Codec,
  executeBase64Codec,
  renderUrlCodec,
  executeUrlCodec,
  renderHtmlCodec,
  executeHtmlCodec,
} from "./encoding-tools.js";
import {
  renderMd5Hash,
  executeMd5Hash,
  renderSha256Hash,
  executeSha256Hash,
  renderJwtDecoder,
  executeJwtDecoder,
} from "./crypto-tools.js";
import {
  renderPasswordGen,
  executePasswordGen,
  renderUuidGen,
  executeUuidGen,
  renderRandomColor,
  executeRandomColor,
} from "./generators-tools.js";
import {
  renderJsonFormatter,
  executeJsonFormatter,
  renderCsvJson,
  executeCsvJson,
  renderMinifyCode,
  executeMinifyCode,
  renderYamlJson,
  executeYamlJson,
  renderHtmlMarkdown,
  executeHtmlMarkdown,
  renderXmlFormatter,
  executeXmlFormatter,
} from "./formatters-tools.js";
import {
  renderUnixTimestamp,
  executeUnixTimestamp,
  renderIso8601Converter,
  executeIso8601Converter,
  renderTimezoneConverter,
  executeTimezoneConverter,
} from "./datetime-tools.js";
import {
  renderIpLocation,
  executeIpLocation,
  renderDnsChecker,
  executeDnsChecker,
  renderPingTest,
  executePingTest,
} from "./network-tools.js";

export const TOOLS = [
  {
    id: "text-reverse",
    name: "Text Reverser",
    category: "text",
    description: "Reverse text strings",
    render: renderTextReverser,
    execute: executeTextReverser,
  },
  {
    id: "text-case",
    name: "Case Converter",
    category: "text",
    description: "Convert text to different cases",
    render: renderCaseConverter,
    execute: executeCaseConverter,
  },
  {
    id: "text-statistics",
    name: "Text Statistics",
    category: "text",
    description: "Count characters, words, and lines",
    render: renderTextStatistics,
    execute: executeTextStatistics,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    category: "text",
    description: "Test and validate regular expressions",
    render: renderRegexTester,
    execute: executeRegexTester,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    category: "text",
    description: "Generate placeholder text",
    render: renderLoremIpsum,
    execute: executeLoremIpsum,
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    category: "text",
    description: "Compare two text blocks",
    render: renderDiffChecker,
    execute: executeDiffChecker,
  },
  {
    id: "string-escaper",
    name: "String Escaper/Unescaper",
    category: "text",
    description: "Escape and unescape strings",
    render: renderStringEscaper,
    execute: executeStringEscaper,
  },
  {
    id: "duplicate-remover",
    name: "Duplicate Line Remover",
    category: "text",
    description: "Remove duplicate lines",
    render: renderDuplicateRemover,
    execute: executeDuplicateRemover,
  },

  {
    id: "base64-codec",
    name: "Base64 Codec",
    category: "encoding",
    description: "Encode/decode Base64 strings",
    render: renderBase64Codec,
    execute: executeBase64Codec,
  },
  {
    id: "url-codec",
    name: "URL Codec",
    category: "encoding",
    description: "Encode/decode URL components",
    render: renderUrlCodec,
    execute: executeUrlCodec,
  },
  {
    id: "html-codec",
    name: "HTML Codec",
    category: "encoding",
    description: "Encode/decode HTML entities",
    render: renderHtmlCodec,
    execute: executeHtmlCodec,
  },
  {
    id: "ascii-unicode",
    name: "ASCII/Unicode Converter",
    category: "encoding",
    description: "Convert text to code points",
    render: renderAsciiUnicode,
    execute: executeAsciiUnicode,
  },
  {
    id: "morse-code",
    name: "Morse Code Converter",
    category: "encoding",
    description: "Text to Morse code and back",
    render: renderMorseCode,
    execute: executeMorseCode,
  },

  {
    id: "md5-hash",
    name: "MD5 Hash",
    category: "crypto",
    description: "Generate MD5 hashes",
    render: renderMd5Hash,
    execute: executeMd5Hash,
  },
  {
    id: "sha256-hash",
    name: "SHA256 Hash",
    category: "crypto",
    description: "Generate SHA-256 hashes",
    render: renderSha256Hash,
    execute: executeSha256Hash,
  },
  {
    id: "sha512-hash",
    name: "SHA-512 Hash",
    category: "crypto",
    description: "Generate SHA-512 hashes",
    render: renderSha512Hash,
    execute: executeSha512Hash,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    category: "crypto",
    description: "Decode JWT tokens",
    render: renderJwtDecoder,
    execute: executeJwtDecoder,
  },
  {
    id: "hmac-generator",
    name: "HMAC Generator",
    category: "crypto",
    description: "Generate HMAC signatures",
    render: renderHmacGenerator,
    execute: executeHmacGenerator,
  },
  {
    id: "crc32-checksum",
    name: "CRC-32 Checksum",
    category: "crypto",
    description: "File integrity verification",
    render: renderCrc32Checksum,
    execute: executeCrc32Checksum,
  },

  {
    id: "password-gen",
    name: "Password Generator",
    category: "generators",
    description: "Generate secure random passwords",
    render: renderPasswordGen,
    execute: executePasswordGen,
  },
  {
    id: "uuid-gen",
    name: "UUID Generator",
    category: "generators",
    description: "Generate UUID v4 identifiers",
    render: renderUuidGen,
    execute: executeUuidGen,
  },
  {
    id: "random-color",
    name: "Random Color",
    category: "generators",
    description: "Generate random hexadecimal colors",
    render: renderRandomColor,
    execute: executeRandomColor,
  },
  {
    id: "qr-code",
    name: "QR Code Generator",
    category: "generators",
    description: "Generate QR codes from text and URLs",
    render: renderQrCode,
    execute: executeQrCode,
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    category: "generators",
    description: "Create URL-friendly slugs",
    render: renderSlugGenerator,
    execute: executeSlugGenerator,
  },
  {
    id: "cron-validator",
    name: "Cron Expression Validator",
    category: "generators",
    description: "Validate cron expressions",
    render: renderCronValidator,
    execute: executeCronValidator,
  },

  {
    id: "json-formatter",
    name: "JSON Formatter",
    category: "formatters",
    description: "Format and validate JSON",
    render: renderJsonFormatter,
    execute: executeJsonFormatter,
  },
  {
    id: "csv-json",
    name: "CSV to JSON",
    category: "formatters",
    description: "Convert CSV to JSON",
    render: renderCsvJson,
    execute: executeCsvJson,
  },
  {
    id: "minify-code",
    name: "Code Minifier",
    category: "formatters",
    description: "Minify CSS, JS, and HTML",
    render: renderMinifyCode,
    execute: executeMinifyCode,
  },
  {
    id: "yaml-json",
    name: "YAML/JSON Converter",
    category: "formatters",
    description: "Convert YAML and JSON",
    render: renderYamlJson,
    execute: executeYamlJson,
  },
  {
    id: "html-markdown",
    name: "HTML/Markdown Converter",
    category: "formatters",
    description: "Convert HTML and Markdown",
    render: renderHtmlMarkdown,
    execute: executeHtmlMarkdown,
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    category: "formatters",
    description: "Format and validate XML",
    render: renderXmlFormatter,
    execute: executeXmlFormatter,
  },

  {
    id: "unix-timestamp",
    name: "Unix Timestamp Converter",
    category: "datetime",
    description: "Convert Unix timestamps",
    render: renderUnixTimestamp,
    execute: executeUnixTimestamp,
  },
  {
    id: "iso8601-converter",
    name: "ISO 8601 Date Converter",
    category: "datetime",
    description: "Convert ISO 8601 dates",
    render: renderIso8601Converter,
    execute: executeIso8601Converter,
  },
  {
    id: "timezone-converter",
    name: "Timezone Converter",
    category: "datetime",
    description: "Convert across timezones",
    render: renderTimezoneConverter,
    execute: executeTimezoneConverter,
  },

  {
    id: "ip-location",
    name: "IP Location Finder",
    category: "network",
    description: "Lookup IP geolocation",
    render: renderIpLocation,
    execute: executeIpLocation,
  },
  {
    id: "dns-checker",
    name: "DNS Checker",
    category: "network",
    description: "Query DNS records",
    render: renderDnsChecker,
    execute: executeDnsChecker,
  },
  {
    id: "ping-test",
    name: "Ping Test",
    category: "network",
    description: "Measure HTTP round-trip time",
    render: renderPingTest,
    execute: executePingTest,
  },
];
